export {Home} from "./Home/Home"
export {Register} from "./Register/Register"
export {Login} from "./Login/Login"
export {ProjectDetail} from "./ProjectDetail/ProjectDetail"
export {Board} from "./Board/Board"